### ISSUE TITLE
Срочно исправьте ошибку

### ISSUE THREAD

**Issue by anxieuse** [lis411/rbt#1]
https://github.com/lis411/rbt/blob/50ff3fbd2ab5ba75ea0cb9c81686a54054bcb4c5/main.cpp#L59

Поменяйте названия свободных функций, мне они не нравятся.

**Comment by anxieuse** [comment]
Названия методов и функций должны быть глаголами.

**Comment by lega4e** [comment]
Умейте отличать методы от свободных функций

**Comment by lega4e** [comment]
Вы неадекватный человек, мистер, предлагаю вам покинуть мой идеально написанный код

**Comment by anxieuse** [comment]
В целом ок, но все перепишите на раст:

- абстракции с нулевой стоимостью
- переместить семантику
- гарантированная безопасность памяти
- темы без данных гонок
- черты на основе признаков
- сопоставление с образцом
- вывод типа
- минимальное время выполнения
- эффективные привязки C
- все это позволит нам эффективно масштабировать лабы.
